#!/bin/bash

mkdir -p certs
if [ -f certs/lswca.pem ]; then
  echo "Certificate already exists."
  exit 0
fi

pushd certs
  openssl genrsa -des3 -out lswca.key 2048
  openssl req -x509 -new -subj '/C=US/ST=Mississippi/L=Ridgeland/O=Longshore Softworks/OU=DevOps/CN=*.longshore.local' -nodes -key lswca.key -sha256 -days 1825 -out lswca.pem
popd
